name: fair-test-workflow2.yml
on:
  workflow_dispatch:


jobs:
  wait:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        wait:
          - { wait: 1 }
          - { wait: 1 }
          - { wait: 1 }
          - { wait: 1 }
          - { wait: 1 }
          - { wait: 1 }
          - { wait: 1 }
          - { wait: 1 }
          - { wait: 1 }
          - { wait: 1 }
          - { wait: 1 }
          - { wait: 1 }
          - { wait: 10 }
          - { wait: 10 }
          - { wait: 10 }
          - { wait: 10 }
          - { wait: 10 }
          - { wait: 10 }
          - { wait: 30 }
          - { wait: 30 }
          - { wait: 30 }
          - { wait: 60 }
    steps:
      - name: Wait
        run: sleep ${{ matrix.wait.wait }}

  wait-120:
    runs-on: ubuntu-latest
    steps:
      - name: Wait 120 seconds
        run: sleep 120
